# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentLobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Lobby'),
        ),
    ]
