# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profile_currentlobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='currentLobby',
            new_name='current_lobby',
        ),
        migrations.AddField(
            model_name='lobby',
            name='is_passcode_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='passcode',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
